# Generated by Django 3.2.15 on 2023-01-19 23:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0002_alter_anime_image'),
        ('users', '0002_commentsanime'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentsanime',
            name='create_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='commentsanime',
            name='anime',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CommentsAnime_Anime', to='anime.anime', verbose_name='Комментируемое аниме'),
        ),
        migrations.AlterField(
            model_name='commentsanime',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор комментария'),
        ),
    ]
