# Generated by Django 3.2.15 on 2023-01-20 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
        ('users', '0003_auto_20230120_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentsanime',
            name='comment',
            field=models.TextField(max_length=400),
        ),
        migrations.CreateModel(
            name='CommentsFilm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField(max_length=400)),
                ('film', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CommentsFilm_Films', to='films.films', verbose_name='Комментируемый фильм')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор комментария')),
            ],
        ),
    ]
