# Generated by Django 3.2.15 on 2023-01-22 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_ratinganime_ratingfilms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentsanime',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='commentsfilm',
            name='rating',
        ),
    ]
