# Generated by Django 3.2.15 on 2023-01-23 23:14

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0002_alter_anime_image'),
        ('users', '0007_auto_20230123_0249'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentsanime',
            name='rating',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='ratinganime',
            name='anime',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='RatingAnime_Anime', to='anime.anime', verbose_name='Оцениваемое аниме'),
        ),
        migrations.AlterField(
            model_name='ratinganime',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор рейтинга'),
        ),
    ]
