# Generated by Django 3.2.15 on 2023-01-16 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0003_anime_animecategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='category',
        ),
        migrations.DeleteModel(
            name='AnimeCategory',
        ),
        migrations.RemoveField(
            model_name='films',
            name='category',
        ),
        migrations.DeleteModel(
            name='Anime',
        ),
        migrations.DeleteModel(
            name='Films',
        ),
        migrations.DeleteModel(
            name='FilmsCategory',
        ),
    ]
